### DISCUSSION TITLE
.yaml files to deploy to kubernetes

### DISCUSSION THREAD

**Discussion by bramnet** [floogulinc/hydrus-web#62] [Ideas]
Since the project is already setup to work with a docker image, could we see the necessary .yaml files to deploy to k8s or k3s in the future?

**Comment by bramnet** [comment]
So... I'm unsubscribing from notifications, but after quite a few tries (forever ago, just forgot about this), I did come up with a yaml manually. Additionally, I'm still trying to figure out how to have it use a different port than 80 because it keeps messing with traefik.
```
apiVersion: apps/v1
kind: Deployment
    spec:
      containers:
        - image: ghcr.io/floogulinc/hydrus-web
          imagePullPolicy: IfNotPresent
          name: hydrus-web
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
              _serviceType: ClusterIP
      dnsConfig:
      dnsPolicy: Default
      hostNetwork: true
      restartPolicy: Always
```
